// SEO data for all pages
export const seoData = {
  index: {
    title: "WE Travel UK | Viagens Exclusivas em Grupo com Acompanhamento Pessoal",
    description: "Descubra destinos incríveis com a WE Travel UK. Viagens exclusivas em grupo para Austrália, Japão, Europa, África e muito mais. Transforme seus sonhos em destinos.",
    keywords: "viagens em grupo, viagens exclusivas, WE Travel UK, destinos internacionais, viagem premium, turismo personalizado",
    ogTitle: "WE Travel UK | Transforme Seus Sonhos em Destinos",
    ogDescription: "Viagens exclusivas em grupo com acompanhamento pessoal. 14+ destinos incríveis pelo mundo.",
  },
  cruzeiroTranspacifico: {
    title: "Cruzeiro Transpacífico 2027 | Sydney → Los Angeles | WE Travel UK",
    description: "Uma jornada de 27 dias que redefine o conceito de viagem premium. Sydney, Polinésia Francesa, Honolulu e Los Angeles. Apenas 20 viajantes. Uma única saída em 2027.",
    keywords: "cruzeiro transpacífico, viagem premium, Sydney, Polinésia Francesa, Honolulu, Los Angeles, Anthem of the Seas, viagem transformadora, cruzeiro luxo",
    ogTitle: "A Travessia dos Eleitos | Cruzeiro Premium Transpacífico 2027",
    ogDescription: "27 dias de transformação. Sydney, Polinésia, Honolulu, Los Angeles. Apenas 20 viajantes.",
  },
  australiaNZ: {
    title: "Austrália & Nova Zelândia 2027 | 18 Dias de Aventura | WE Travel UK",
    description: "Explore a Oceania em uma jornada de 18 dias. Sydney, Cairns, Melbourne, Queenstown e Auckland. Cangurus, Grande Barreira de Coral e paisagens deslumbrantes.",
    keywords: "viagem austrália, nova zelândia, sydney, melbourne, queenstown, auckland, grande barreira coral, cangurus, viagem oceania",
    ogTitle: "Austrália & Nova Zelândia | A Jornada Completa pela Oceania",
    ogDescription: "18 dias de transformação pela Oceania. Sydney, Cairns, Melbourne, Queenstown e Auckland.",
  },
  cruzeiroNorte: {
    title: "Cruzeiro Norte Europeu 2026 | Islândia, Noruega & Escócia | WE Travel UK",
    description: "Navegue pelos fjords noruegueses, explore a Islândia e caminhe pelas ruas históricas de Edimburgo. 21 dias de expedição pelo Norte da Europa.",
    keywords: "cruzeiro norte europeu, islândia, noruega, escócia, fjords, aurora boreal, edimburgo, viking, cruzeiro luxo europa",
    ogTitle: "Cruzeiro Norte Europeu | A Expedição pelo Norte da Europa",
    ogDescription: "21 dias navegando por Islândia, Noruega e Escócia. Fjords, aurora boreal e história.",
  },
  japaoChina: {
    title: "Japão & China 2026 | Templos, Monte Fuji & Grande Muralha | WE Travel UK",
    description: "20 dias explorando o Japão e a China. Kyoto, Tóquio, Monte Fuji, Beijing, Grande Muralha e Xangai. Uma imersão cultural completa no Oriente.",
    keywords: "viagem japão, viagem china, monte fuji, grande muralha, kyoto, tóquio, beijing, xangai, templos japão, cultura oriental",
    ogTitle: "Japão & China | A Jornada pelo Oriente",
    ogDescription: "20 dias de imersão cultural. Kyoto, Tóquio, Monte Fuji, Beijing, Grande Muralha e Xangai.",
  },
  reinoUnido: {
    title: "Reino Unido 2026 | Londres, Highlands & Edimburgo | WE Travel UK",
    description: "15 dias pelo Reino Unido. Londres, Cotswolds, Bath, Highlands escocesas e Edimburgo. História, castelos e paisagens de tirar o fôlego.",
    keywords: "viagem reino unido, londres, escócia, highlands, edimburgo, cotswolds, castelos, big ben, viagem inglaterra",
    ogTitle: "Reino Unido | A Travessia Pelas Terras Britânicas",
    ogDescription: "15 dias de transformação. Londres, Highlands e Edimburgo. História e paisagens incríveis.",
  },
  suicaTrem: {
    title: "Suíça de Trem 2026 | Alpes Suíços & Trens Panorâmicos | WE Travel UK",
    description: "14 dias explorando a Suíça de trem. Zermatt, Matterhorn, Glacier Express, Interlaken e Lucerna. A jornada mais cênica do mundo.",
    keywords: "viagem suíça, alpes suíços, trem suíça, glacier express, matterhorn, zermatt, interlaken, lucerna, viagem de trem",
    ogTitle: "Suíça de Trem | A Jornada Pelos Alpes",
    ogDescription: "14 dias nos trens panorâmicos da Suíça. Matterhorn, Glacier Express e paisagens alpinas.",
  },
  africaMauricio: {
    title: "África do Sul & Ilhas Maurício 2026 | Safári & Praias Paradisíacas | WE Travel UK",
    description: "16 dias de aventura. Cape Town, safári na reserva privada e praias paradisíacas das Ilhas Maurício. Big Five e relaxamento tropical.",
    keywords: "viagem áfrica sul, ilhas maurício, safári, cape town, big five, table mountain, praias maurício, lua de mel",
    ogTitle: "África do Sul & Ilhas Maurício | Safári e Praias Paradisíacas",
    ogDescription: "16 dias de transformação. Cape Town, safári com Big Five e praias das Ilhas Maurício.",
  },
  chinaMaravilhas: {
    title: "China Maravilhas Culturais 2026 | Beijing, Xi'an & Xangai | WE Travel UK",
    description: "19 dias descobrindo a China milenar. Grande Muralha, Cidade Proibida, Guerreiros de Terracota, Hangzhou e Xangai moderna.",
    keywords: "viagem china, grande muralha, cidade proibida, guerreiros terracota, beijing, xian, xangai, hangzhou, cultura chinesa",
    ogTitle: "China Maravilhas Culturais | A Jornada Pela China Milenar",
    ogDescription: "19 dias explorando a China. Grande Muralha, Guerreiros de Terracota e metrópoles modernas.",
  },
  pugliaAmalfi: {
    title: "Puglia & Costa Amalfitana 2026 | Sul da Itália | WE Travel UK",
    description: "16 dias pelo sul da Itália. Alberobello, Polignano a Mare, Positano, Amalfi e Ravello. Trulli, praias e a dolce vita italiana.",
    keywords: "viagem itália, puglia, costa amalfitana, positano, amalfi, alberobello, trulli, polignano mare, sul itália",
    ogTitle: "Puglia & Costa Amalfitana | O Melhor do Sul da Itália",
    ogDescription: "16 dias pela Puglia e Costa Amalfitana. Trulli, vilarejos e as praias mais bonitas da Itália.",
  },
  tailandiaDubai: {
    title: "Tailândia & Dubai 2026 | Festival das Lanternas & Modernidade | WE Travel UK",
    description: "19 dias de contrastes. Bangkok, Chiang Mai, Festival das Lanternas, praias de Krabi e a modernidade de Dubai. Oriente em sua essência.",
    keywords: "viagem tailândia, viagem dubai, bangkok, chiang mai, krabi, festival lanternas, burj khalifa, templos tailândia",
    ogTitle: "Tailândia & Dubai | Do Tradicional ao Moderno",
    ogDescription: "19 dias de transformação. Templos, Festival das Lanternas, praias e a grandiosidade de Dubai.",
  },
  ushuaiaCalafate: {
    title: "Ushuaia, El Calafate & Buenos Aires 2026 | Patagônia Argentina | WE Travel UK",
    description: "9 dias na Patagônia Argentina. Ushuaia (Fim do Mundo), Glaciar Perito Moreno, El Calafate e Buenos Aires. Aventura no extremo sul.",
    keywords: "viagem patagônia, ushuaia, el calafate, perito moreno, glaciar, buenos aires, fim do mundo, argentina, tango",
    ogTitle: "Ushuaia, El Calafate & Buenos Aires | A Aventura na Patagônia",
    ogDescription: "9 dias no extremo sul. Ushuaia, Glaciar Perito Moreno e Buenos Aires.",
  },
  mercadosNatal: {
    title: "Mercados de Natal 2026 | Alsácia & Suíça | WE Travel UK",
    description: "13 dias de magia natalina. Estrasburgo, Colmar, mercados de Natal da Alsácia e paisagens nevadas da Suíça. O Natal mais encantador.",
    keywords: "mercados natal, estrasburgo, colmar, alsácia, natal suíça, viagem natal, mercado natalino, frança, inverno europa",
    ogTitle: "Mercados de Natal | A Magia do Natal na Europa",
    ogDescription: "13 dias de magia. Mercados de Natal na Alsácia e Suíça. O Natal mais encantador do mundo.",
  },
  laponiaTromso: {
    title: "Lapônia & Tromsø 2027 | Aurora Boreal & Ártico | WE Travel UK",
    description: "16 dias no Ártico. Lapônia finlandesa, Tromsø, aurora boreal, huskies, renas e hotel de gelo. Uma experiência única no extremo norte.",
    keywords: "aurora boreal, lapônia, tromsø, finlândia, noruega, ártico, husky, hotel gelo, papai noel, inverno",
    ogTitle: "Lapônia & Tromsø | A Magia do Ártico",
    ogDescription: "16 dias no extremo norte. Aurora boreal, huskies, hotel de gelo e experiências árticas únicas.",
  },
  greciaAlemDoObvio: {
    title: "Grécia Além do Óbvio 2026 | Zakynthos, Santorini & Mykonos | WE Travel UK",
    description: "16 dias descobrindo a Grécia autêntica. Atenas, Zakynthos (Navagio Beach), Cephalonia, Santorini e Mykonos. As ilhas gregas como você nunca viu.",
    keywords: "viagem grécia, zakynthos, santorini, mykonos, navagio beach, ilhas gregas, atenas, cephalonia, mediterrâneo",
    ogTitle: "Grécia Além do Óbvio | Descubra as Ilhas Gregas",
    ogDescription: "16 dias pelas ilhas gregas. Zakynthos, Santorini, Mykonos e praias paradisíacas.",
  },
};
